//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
// 
namespace iExchange.DealingConsole.ParticipantServices
{
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.ComponentModel;
	using System.Web.Services;


	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name = "ParticipantServicesSoap", Namespace = "http://tempuri.org/")]
	public class ParticipantServices : System.Web.Services.Protocols.SoapHttpClientProtocol
	{

		/// <remarks/>
		public ParticipantServices()
		{
			string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["iExchange.DealingConsole.ParticipantServices.ParticipantServices"];
			if ((urlSetting != null))
			{
				this.Url = string.Concat(urlSetting, "");
			}
			else
			{
				this.Url = "http://webserver/SecuritySystem/Web/Service/ParticipantServices.asmx";
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateParticipantByDataSet", RequestElementName = "UpdateParticipantByDataSet", RequestNamespace = "http://tempuri.org/", ResponseElementName = "UpdateParticipantByDataSetResponse", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		[return: System.Xml.Serialization.XmlElementAttribute("UpdateParticipantByDataSetResult")]
		public bool UpdateParticipant(System.Data.DataSet participants, System.Guid loginUserID, out string message)
		{
			object[] results = this.Invoke("UpdateParticipant", new object[] {
                        participants,
                        loginUserID});
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginUpdateParticipant(System.Data.DataSet participants, System.Guid loginUserID, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("UpdateParticipant", new object[] {
                        participants,
                        loginUserID}, callback, asyncState);
		}

		/// <remarks/>
		public bool EndUpdateParticipant(System.IAsyncResult asyncResult, out string message)
		{
			object[] results = this.EndInvoke(asyncResult);
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePassword", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool UpdatePassword(System.Guid participantID, string password, System.Guid loginUserID, out string message)
		{
			object[] results = this.Invoke("UpdatePassword", new object[] {
                        participantID,
                        password,
                        loginUserID});
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginUpdatePassword(System.Guid participantID, string password, System.Guid loginUserID, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("UpdatePassword", new object[] {
                        participantID,
                        password,
                        loginUserID}, callback, asyncState);
		}

		/// <remarks/>
		public bool EndUpdatePassword(System.IAsyncResult asyncResult, out string message)
		{
			object[] results = this.EndInvoke(asyncResult);
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.WebMethodAttribute(MessageName = "UpdateParticipant1")]
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateParticipant", RequestElementName = "UpdateParticipant", RequestNamespace = "http://tempuri.org/", ResponseElementName = "UpdateParticipantResponse", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		[return: System.Xml.Serialization.XmlElementAttribute("UpdateParticipantResult")]
		public bool UpdateParticipant(System.Guid participantID, string participantName, string participantLoginName, string password, System.Guid loginUserID, out string message)
		{
			object[] results = this.Invoke("UpdateParticipant1", new object[] {
                        participantID,
                        participantName,
                        participantLoginName,
                        password,
                        loginUserID});
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginUpdateParticipant1(System.Guid participantID, string participantName, string participantLoginName, string password, System.Guid loginUserID, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("UpdateParticipant1", new object[] {
                        participantID,
                        participantName,
                        participantLoginName,
                        password,
                        loginUserID}, callback, asyncState);
		}

		/// <remarks/>
		public bool EndUpdateParticipant1(System.IAsyncResult asyncResult, out string message)
		{
			object[] results = this.EndInvoke(asyncResult);
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateParticipant", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool CreateParticipant(System.Guid participantID, string participantName, string participantLoginName, string participantPassword, System.Guid participantTypeID, System.Guid parentParticipantID, System.Guid loginUserID, out string message)
		{
			object[] results = this.Invoke("CreateParticipant", new object[] {
                        participantID,
                        participantName,
                        participantLoginName,
                        participantPassword,
                        participantTypeID,
                        parentParticipantID,
                        loginUserID});
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginCreateParticipant(System.Guid participantID, string participantName, string participantLoginName, string participantPassword, System.Guid participantTypeID, System.Guid parentParticipantID, System.Guid loginUserID, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("CreateParticipant", new object[] {
                        participantID,
                        participantName,
                        participantLoginName,
                        participantPassword,
                        participantTypeID,
                        parentParticipantID,
                        loginUserID}, callback, asyncState);
		}

		/// <remarks/>
		public bool EndCreateParticipant(System.IAsyncResult asyncResult, out string message)
		{
			object[] results = this.EndInvoke(asyncResult);
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteParticipant", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool DeleteParticipant(System.Guid participantID, System.Guid loginUserID, out string message)
		{
			object[] results = this.Invoke("DeleteParticipant", new object[] {
                        participantID,
                        loginUserID});
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginDeleteParticipant(System.Guid participantID, System.Guid loginUserID, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("DeleteParticipant", new object[] {
                        participantID,
                        loginUserID}, callback, asyncState);
		}

		/// <remarks/>
		public bool EndDeleteParticipant(System.IAsyncResult asyncResult, out string message)
		{
			object[] results = this.EndInvoke(asyncResult);
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateParticipantRelation", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool CreateParticipantRelation(System.Guid participantID, System.Guid parentID, System.Guid loginUserID, out string message)
		{
			object[] results = this.Invoke("CreateParticipantRelation", new object[] {
                        participantID,
                        parentID,
                        loginUserID});
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginCreateParticipantRelation(System.Guid participantID, System.Guid parentID, System.Guid loginUserID, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("CreateParticipantRelation", new object[] {
                        participantID,
                        parentID,
                        loginUserID}, callback, asyncState);
		}

		/// <remarks/>
		public bool EndCreateParticipantRelation(System.IAsyncResult asyncResult, out string message)
		{
			object[] results = this.EndInvoke(asyncResult);
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteParticipantRelation", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool DeleteParticipantRelation(System.Guid participantID, System.Guid parentID, System.Guid loginUserID, out string message)
		{
			object[] results = this.Invoke("DeleteParticipantRelation", new object[] {
                        participantID,
                        parentID,
                        loginUserID});
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginDeleteParticipantRelation(System.Guid participantID, System.Guid parentID, System.Guid loginUserID, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("DeleteParticipantRelation", new object[] {
                        participantID,
                        parentID,
                        loginUserID}, callback, asyncState);
		}

		/// <remarks/>
		public bool EndDeleteParticipantRelation(System.IAsyncResult asyncResult, out string message)
		{
			object[] results = this.EndInvoke(asyncResult);
			message = ((string)(results[1]));
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckParticipantRelation", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool CheckParticipantRelation(System.Guid participantID, System.Guid parentID, System.Guid loginUserID)
		{
			object[] results = this.Invoke("CheckParticipantRelation", new object[] {
                        participantID,
                        parentID,
                        loginUserID});
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginCheckParticipantRelation(System.Guid participantID, System.Guid parentID, System.Guid loginUserID, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("CheckParticipantRelation", new object[] {
                        participantID,
                        parentID,
                        loginUserID}, callback, asyncState);
		}

		/// <remarks/>
		public bool EndCheckParticipantRelation(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetParticipants", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet GetParticipants(System.Guid loginUserID)
		{
			object[] results = this.Invoke("GetParticipants", new object[] {
                        loginUserID});
			return ((System.Data.DataSet)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginGetParticipants(System.Guid loginUserID, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("GetParticipants", new object[] {
                        loginUserID}, callback, asyncState);
		}

		/// <remarks/>
		public System.Data.DataSet EndGetParticipants(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetParticipantTypes", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet GetParticipantTypes(System.Guid loginUserID)
		{
			object[] results = this.Invoke("GetParticipantTypes", new object[] {
                        loginUserID});
			return ((System.Data.DataSet)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginGetParticipantTypes(System.Guid loginUserID, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("GetParticipantTypes", new object[] {
                        loginUserID}, callback, asyncState);
		}

		/// <remarks/>
		public System.Data.DataSet EndGetParticipantTypes(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginByAdministrator", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Guid LoginByAdministrator(string participantLoginName, string participantPassword, out string message)
		{
			object[] results = this.Invoke("LoginByAdministrator", new object[] {
                        participantLoginName,
                        participantPassword});
			message = ((string)(results[1]));
			return ((System.Guid)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginLoginByAdministrator(string participantLoginName, string participantPassword, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("LoginByAdministrator", new object[] {
                        participantLoginName,
                        participantPassword}, callback, asyncState);
		}

		/// <remarks/>
		public System.Guid EndLoginByAdministrator(System.IAsyncResult asyncResult, out string message)
		{
			object[] results = this.EndInvoke(asyncResult);
			message = ((string)(results[1]));
			return ((System.Guid)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Guid Login(string participantLoginName, string participantPassword)
		{
			object[] results = this.Invoke("Login", new object[] {
                        participantLoginName,
                        participantPassword});
			return ((System.Guid)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginLogin(string participantLoginName, string participantPassword, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("Login", new object[] {
                        participantLoginName,
                        participantPassword}, callback, asyncState);
		}

		/// <remarks/>
		public System.Guid EndLogin(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Guid)(results[0]));
		}
	}
}
